title: Trevor Harron # your name (or website title) here
logo: "/images/tre-logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Game designer and Programmer with a Masters from DigiPen Institute of Technology in Computer Science and a Bachelors of Computer Science from Middlebury College.
  4 years of Professional Software Development experience in bother developer and development testing roles. Proficient in C/C++, Java, C#, and Python. Experienced 
  working on teams of all sizes and collaborating with multiple disciplines. 
  <br><br>
  I have published two board games and an expansion with successful Kickstarter campaigns. I also supplemented my 
  design experience with additional course work. Lead Designer on multiple School Game Projects. Currently learning Unreal and Unity while working 
  on my own game projects and engine.
  <br><br>
  <a href="https://www.linkedin.com/in/trharron/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
